package com.edusummarize.models;

import java.sql.Timestamp;
import java.time.LocalDateTime;

/**
 * Payment Model Class - Matches Class Diagram
 * 
 * CLASS DIAGRAM: Subscription → Payment (Directed Association, 1 to 1..*)
 * 
 * CLASS DIAGRAM ATTRIBUTES:
 * - paymentID: int
 * - subscriptionID: int
 * - userID: int
 * - amount: double
 * - paymentDate: Date
 * - transactionStatus: String
 * 
 * CLASS DIAGRAM OPERATIONS:
 * - processPayment(): boolean
 */
public class Payment {
    // Attributes (from class diagram)
    private int paymentID;
    private int subscriptionID;
    private int userID;
    private double amount;
    private Timestamp paymentDate;
    private String transactionStatus;   // "Success", "Pending", "Failed", "Refunded"
    
    // Additional attributes
    private String paymentMethod;       // "Credit Card", "Online Banking", "E-Wallet"
    private String transactionReference;
    private String description;
    
    // Transaction status constants
    public static final String STATUS_SUCCESS = "Success";
    public static final String STATUS_PENDING = "Pending";
    public static final String STATUS_FAILED = "Failed";
    public static final String STATUS_REFUNDED = "Refunded";
    
    // Constructors
    public Payment() {
        this.paymentDate = Timestamp.valueOf(LocalDateTime.now());
        this.transactionStatus = STATUS_PENDING;
    }
    
    public Payment(int paymentID, int subscriptionID, int userID, double amount) {
        this();
        this.paymentID = paymentID;
        this.subscriptionID = subscriptionID;
        this.userID = userID;
        this.amount = amount;
    }
    
    // CLASS DIAGRAM OPERATIONS
    
    /**
     * Operation: processPayment()
     * Processes the payment transaction
     * @return true if payment processed successfully
     */
    public boolean processPayment() {
        // Validate payment details
        if (amount <= 0) {
            System.err.println("Invalid payment amount: " + amount);
            this.transactionStatus = STATUS_FAILED;
            return false;
        }
        
        if (userID <= 0) {
            System.err.println("Valid User ID is required for payment");
            this.transactionStatus = STATUS_FAILED;
            return false;
        }
        
        if (subscriptionID <= 0) {
            System.err.println("Valid Subscription ID is required for payment");
            this.transactionStatus = STATUS_FAILED;
            return false;
        }
        
        // Generate payment ID if not exists
        if (paymentID <= 0) {
            this.paymentID = generatePaymentID();
        }
        
        // Generate transaction reference
        this.transactionReference = generateTransactionReference();
        
        // Set payment date
        this.paymentDate = Timestamp.valueOf(LocalDateTime.now());
        
        // Simulate payment processing
        // In real implementation, this would integrate with payment gateway
        try {
            // Simulate payment gateway call
            System.out.println("Processing payment...");
            System.out.println("Payment ID: " + paymentID);
            System.out.println("Amount: RM " + amount);
            System.out.println("User ID: " + userID);
            System.out.println("Subscription ID: " + subscriptionID);
            
            // Simulate successful payment (in real system, this would be actual API response)
            this.transactionStatus = STATUS_SUCCESS;
            System.out.println("Payment processed successfully!");
            
            return true;
            
        } catch (Exception e) {
            System.err.println("Payment processing failed: " + e.getMessage());
            this.transactionStatus = STATUS_FAILED;
            return false;
        }
    }
    
    /**
     * Helper method: Generate unique payment ID
     */
    private int generatePaymentID() {
        // In production, this would be auto-generated by database
        return (int)(System.currentTimeMillis() % Integer.MAX_VALUE);
    }
    
    /**
     * Helper method: Generate transaction reference number
     */
    private String generateTransactionReference() {
        return "TXN-" + System.currentTimeMillis();
    }
    
    /**
     * Helper method: Check if payment is pending
     */
    public boolean isPending() {
        return transactionStatus.equals(STATUS_PENDING);
    }
    
    /**
     * Helper method: Check if payment failed
     */
    public boolean isFailed() {
        return transactionStatus.equals(STATUS_FAILED);
    }
    
    /**
     * Helper method: Check if payment is successful
     */
    public boolean isSuccess() {
        return transactionStatus.equals(STATUS_SUCCESS);
    }
    
    // Getters and Setters
    
    public int getPaymentID() {
        return paymentID;
    }
    
    public void setPaymentID(int paymentID) {
        this.paymentID = paymentID;
    }
    
    public int getSubscriptionID() {
        return subscriptionID;
    }
    
    public void setSubscriptionID(int subscriptionID) {
        this.subscriptionID = subscriptionID;
    }
    
    public int getUserID() {
        return userID;
    }
    
    public void setUserID(int userID) {
        this.userID = userID;
    }
    
    public double getAmount() {
        return amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    
    public Timestamp getPaymentDate() {
        return paymentDate;
    }
    
    public void setPaymentDate(Timestamp paymentDate) {
        this.paymentDate = paymentDate;
    }
    
    public String getTransactionStatus() {
        return transactionStatus;
    }
    
    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    
    public String getPaymentMethod() {
        return paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    
    public String getTransactionReference() {
        return transactionReference;
    }
    
    public void setTransactionReference(String transactionReference) {
        this.transactionReference = transactionReference;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Override
    public String toString() {
        return "Payment{" +
                "paymentID=" + paymentID +
                ", userID=" + userID +
                ", amount=RM" + amount +
                ", transactionStatus='" + transactionStatus + '\'' +
                ", paymentDate=" + paymentDate +
                '}';
    }
}
